### ISSUE TITLE
How to resize UI?

### ISSUE THREAD

**Issue by trini0n** [Foglio1024/Tera-custom-cooldowns#1]
Is there any way that we can resize the boss gauge and character windows UI? I've looked through the files in the Windows folder and nothing seems to change.

**Comment by Foglio1024** [comment]
There's no way to do it at the moment. I'm mainly focusing on performance and optimizations. It will be added in the future together with per-element settings.

**Comment by trini0n** [comment]
I see, got it. Thanks. Also wondering to get updates for TCC, do we just update the TCC.UI folder or is there something else we have to do?

**Comment by Foglio1024** [comment]
You can just replace the old version with the new one, at least for earlier versions. I'll add auto-updates at some point in the future.

**Comment by trini0n** [comment]
Right, so you can just overwrite the TCC.UI folder? The link for the base files (https://drive.google.com/file/d/0B_Cqa6A1OUxdYURsQVNVNTN4cDQ/view) are all the same?
