### ISSUE TITLE
Crash with JTERA

### ISSUE THREAD

**Issue by nagi666** [Foglio1024/Tera-custom-cooldowns#10]
In Japan TERA environment TCC crashes if it is a job other than reaper, Warrior, Gunner.
I confirmed it with Version 1.3.

**Comment by Foglio1024** [comment]
Does it crash after connecting to the server or later?

**Comment by nagi666** [comment]
It is after the server connection.　　　　Crash after selecting a character.

**Comment by nagi666** [comment]
After choosing a character

**Comment by nagi666** [comment]
Three jobs will work normally

**Comment by Foglio1024** [comment]
It should now work with version 0.1.5
