### ISSUE TITLE
TERA NA - Char selection error

### ISSUE THREAD

**Issue by f3ck4r** [Foglio1024/Tera-custom-cooldowns#100]
[error.txt](https://github.com/Foglio1024/Tera-custom-cooldowns/files/1808351/error.txt)

**Comment by Mhoz** [comment]
Same here, uploading in case it helps 
[error.txt](https://github.com/Foglio1024/Tera-custom-cooldowns/files/1811722/error.txt)

**Comment by Gl0** [comment]
as a temporary workaround - replace items-NA.tsv with [items-NA.tsv](https://github.com/neowutran/TeraDpsMeterData/raw/master/items/items-NA.tsv)

**Comment by Foglio1024** [comment]
Fixed in d89b65ec134686ea526110baa33fc53da7568c2d
