### ISSUE TITLE
Revert chat window!!

### ISSUE THREAD

**Issue by Shrubbity** [Foglio1024/Tera-custom-cooldowns#101]
How am I meant to revert the chat window? It's royally screwed it. I don't want to use TCC anymore and I can't change it back despite trying different S1UIChat2 mods. Help please!

**Comment by Foglio1024** [comment]
Just restore your old `S1UI/S1UI_Chat2.gpk` and/or delete `_S1UI/S1UI_Chat2.gpk`.

**Comment by Shrubbity** [comment]
It genuinely didn't change anything, I even replaced the S1UI_Chat2 file in the S1UI just in case I'd mistakenly replaced that. The changes seems to commit server side, because I tried my completely stock laptop and the window was still screwed. The only difference was that I could click the gear icon in order to revert the chat window position, and that fixed it!

**Comment by Shrubbity** [comment]
Okay well, it did seem to be something in my S1UI folder that was amiss, but it wasn't S1UI_Chat2.gpk since I replaced that many times.

**Comment by Gl0** [comment]
after restoring original GPK/Owyn's mod you need to reset settings via chatbox settings menu ingame.
