### ISSUE TITLE
Moving individual party windows?

### ISSUE THREAD

**Issue by Yahiiii** [Foglio1024/Tera-custom-cooldowns#103]
Hey I was just wondering if there was a function to move individual party windows? Mine currently seems to have a column for each role type and as such it stretches pretty far across my screen. I can't scale it down otherwise it becomes too small. Also, how do I access the info window? I can't seem to find it anywhere.

**Comment by Foglio1024** [comment]
Party members are organized in 3 columns by design and cannot be moved individually. Info window can be accessed using the floating button at the left screen border as stated in the wiki.

**Comment by Yahiiii** [comment]
Will there be a function to move party members in the future?

**Comment by Foglio1024** [comment]
I would like to add it, but it requires time and I don't have much at the moment. Also I don't know if it will impact performance.
