### ISSUE TITLE
Can't see the "new hud"

### ISSUE THREAD

**Issue by JouenV** [Foglio1024/Tera-custom-cooldowns#108]
When i open the game there isnt anything ( not even in the top-left corner) i have windowed-fullscreen and have checked all the things, when i disable and re-enable one of the HUD'S (for exemple the charecter window settings) it appears for a second in the topleft but then it disappears again. Please help.

PD: Version .31

**Comment by JouenV** [comment]
When i disable the transparency it appears a black square with the shape of the hud

**Comment by Foglio1024** [comment]
Is TCC icon green in task bar?
