### ISSUE TITLE
Auto Update not working

### ISSUE THREAD

**Issue by iurimcabral** [Foglio1024/Tera-custom-cooldowns#117]
Auto Update fails for both new versions and icon database, i've seen this being reported a couple of times already but with no logs attached, so i'm uploading mine in case it's of any use.

[update-error.txt](https://github.com/Foglio1024/Tera-custom-cooldowns/files/1998959/update-error.txt)

**Comment by iTzHellArrow** [comment]
If you do not let me update is there a way to update manually?

**Comment by trini0n** [comment]
Yes, go here (https://github.com/Foglio1024/Tera-custom-cooldowns/releases) and download the latest TCC and unzip it.

**Comment by iTzHellArrow** [comment]
thank you very much

**Comment by iTzHellArrow** [comment]
with this one that you download for this page that I do? Is it a proxy module?
