### ISSUE TITLE
Slayer - Class window bug

### ISSUE THREAD

**Issue by Tripater** [Foglio1024/Tera-custom-cooldowns#119]
The Class window for the Slayer is missing the In Cold Blood icon and both the CD and the skill duration don't get displayed. In other words the ICB part of the window is completely non-functional, as can be seen here:

![icb](https://user-images.githubusercontent.com/39249316/39973687-1667ea24-5723-11e8-97db-85ee4724e592.png)

The part of the window that manages Overhand Strike is working just fine, so it may be related to the skill ID, but that's just a shot in the dark.

**Comment by concert2011** [comment]
\TCC.Core\Controls\ClassBars\SlayerBar.xaml

[37]
<local:BuffCooldownControl DataContext="{Binding Instance.InColdBlood}" Padding="20" Margin="-20" />

>>
[37]
<local:BuffCooldownControl DataContext="{Binding InColdBlood}" Padding="20" Margin="-20" />


would be fix this problem.

**Comment by Foglio1024** [comment]
Thanks, that's probably the issue.
