### ISSUE TITLE
Buff Bar disappeared

### ISSUE THREAD

**Issue by Legsbiter** [Foglio1024/Tera-custom-cooldowns#126]
Since the new update, I can no longer see my buffs

**Comment by Foglio1024** [comment]
Could you post post `tcc-config.xml` here please?

**Comment by Legsbiter** [comment]
Where would I find that?

**Comment by Legsbiter** [comment]
Is it copy pasting correctly on your side? I only see numbers

**Comment by Foglio1024** [comment]
I see numbers too, upload it somewhere and paste the link.

**Comment by Legsbiter** [comment]
https://pastebin.com/kmx61WX1

**Comment by Foglio1024** [comment]
Buff window ended up above the screen somehow. Change that `Y="-1"` to `Y="0"`.

**Comment by Legsbiter** [comment]
Thank you!
