### ISSUE TITLE
RR bosses not showing up on the boss hp bar.

### ISSUE THREAD

**Issue by Heitorion** [Foglio1024/Tera-custom-cooldowns#134]
I've tried everything.  I updated tcc, manually changed their boss ids to show as bosses in the monster file, and tried downloading someone's elses tcc who had it working for them.

**Comment by Aoki5432** [comment]
Mine also shows the same problem. It shows the boss hp as "add". Also, DoT not showing on buff window.

**Comment by Aoki5432** [comment]
NA
