### ISSUE TITLE
Can't update Icon Database

### ISSUE THREAD

**Issue by steasz** [Foglio1024/Tera-custom-cooldowns#136]
I'm playing without any icons ingame since the release of awakening because everytime i try to update the database it says : "error while checking database update".
Manually downloading the newest version didnt work out as well. 
How to fix ??

**Comment by steasz** [comment]
In the resources file im missing the file called images, maybe someone could upload it? I think that might be the problem but i can't find it anywhere

**Comment by Foglio1024** [comment]
https://github.com/Foglio1024/Tera-custom-cooldowns/wiki#manual-icon-database-download
