### ISSUE TITLE
LFG applicant info list opening automatically

### ISSUE THREAD

**Issue by MuffinName** [Foglio1024/Tera-custom-cooldowns#138]
Every time the party composition changes in any way the party applicant info window opens, i.e. when someone logs in or out, or joins or leaves the party. This is especially a problem when a lot of people are being invited into a raid group in quick succession.

**Comment by scarfcat** [comment]
I have the very same problem and would like to report more problems that seem related to this issue.

First issue:

The wiki states that the S1UI_PartyBoard.gpk should be replaced with the empty gpk file to use the LFG window.

I did this, but the TCC LFG window would no longer populate with a hidden S1UI_PartyBoard.

So I had to revert the gpk file. It works now but I both UIs will pop up when I open LFG. 

Second issue: 
Disabling the TCC LFG window will not allow the ingame LFG UI to be populated.

I am also using the tcc-stub proxy module with Caali's proxy

**Comment by MuffinName** [comment]
Maybe also related, even before replacing `PartyBoardMemberInfo.gpk`, when I click on the LFG Bar on top of the chat nothing happens when the LFG is still there, but if it isn't there anymore I get a "linked text no longer valid" message ingame. Is there some way to make the LFG Bar functional again?

**Comment by Foglio1024** [comment]
Fixed in v1.0.9.

**Comment by scarfcat** [comment]
Thanks for your hard work @Foglio1024
