### ISSUE TITLE
Crash upon server connect

### ISSUE THREAD

**Issue by fractured** [Foglio1024/Tera-custom-cooldowns#14]
Crashing upon connecting to the TERA servers every time.
Added the error log.
[error.txt](https://github.com/Foglio1024/Tera-custom-cooldowns/files/933913/error.txt)

**Comment by Foglio1024** [comment]
Looks like a problem with characters parser. I'll fix it soon.

**Comment by Foglio1024** [comment]
Fixed in [v0.1.6](https://github.com/Foglio1024/Tera-custom-cooldowns/releases/tag/v0.1.6).
