### ISSUE TITLE
Chat window

### ISSUE THREAD

**Issue by Yafity** [Foglio1024/Tera-custom-cooldowns#140]
When somebody is trying to link an item chat shows an empty message

**Comment by Foglio1024** [comment]
Which item?

**Comment by Yafity** [comment]
Different items(it's outfit i think). I think it depends on item linked properly or not.

**Comment by Yafity** [comment]
![image](https://user-images.githubusercontent.com/34633830/40272386-084e354c-5bb5-11e8-9ba5-6a61082f86ee.png)
PS Nothing happens when you trying to open link

**Comment by Gl0** [comment]
can you open that link with ingame chat?

**Comment by Yafity** [comment]
no

**Comment by Gl0** [comment]
Then blame Destiny Development for not fixing chat links after security update.

**Comment by Foglio1024** [comment]
Message parser probably encountered an error and left empty message there.

**Comment by Gl0** [comment]
if that message is from you friend - tell him to go to forum and get fixed S1UI_Chat2.gpk

**Comment by Yafity** [comment]
I mean is it possible to make it as a message to see what's written?

**Comment by Foglio1024** [comment]
I'm not sure if it's still there, but once I made TCC dump content for wrong messages in some txt file in TCC folder. You could send me that if it's there.

**Comment by Yafity** [comment]
[link-test.txt](https://github.com/Foglio1024/Tera-custom-cooldowns/files/2019781/link-test.txt)
chat_link&:tcc:1:tcc:213277@495833709@Девушка:tcc:
chat_link&:tcc:1:tcc:88375@511086802:tcc:
chat_link&:tcc:1:tcc:88634@518371767@utamuto:tcc:
chat_link&:tcc:1:tcc:83045@518570523@Stripperpole:tcc:
chat_link&:tcc:1:tcc:83045@518570523@Stripperpole:tcc:
chat_link&:tcc:1:tcc:83045@518570523@Stripperpole:tcc:
chat_link&:tcc:3:tcc:9999_14_9739@9739@56070.000000,-94170.000000,2669.856934:tcc:
chat_link&:tcc:3:tcc:9999_14_9739@9739@55140.000000,-94110.000000,2669.856934:tcc:
