### ISSUE TITLE
TCC runs slowly

### ISSUE THREAD

**Issue by Yafity** [Foglio1024/Tera-custom-cooldowns#142]
TCC runs after 2 minutes when you log on char

**Comment by Foglio1024** [comment]
Check memory/cpu usage.

**Comment by Yafity** [comment]
<10% CPU usage and 9GB of RAM when loading
<1% CPU usage and 4GB RAM after

**Comment by Yafity** [comment]
15-17% CPU from 4GB to 9GB RAM when loading

**Comment by Foglio1024** [comment]
Is there any specific moment when it happens?

**Comment by Yafity** [comment]
Every time I log on char

**Comment by Foglio1024** [comment]
Can you zip whole TCC folder and upload it somewhere?

**Comment by Yafity** [comment]
https://drive.google.com/file/d/1Y1-7K0iVOLOz4Cyb14N5i8Txa3CTn0ZD/view?usp=sharing

**Comment by Foglio1024** [comment]
Delete `lancer-skills.xml` from `resources/skills/` and report back if it happens again.

**Comment by Yafity** [comment]
thanks a lot<3
