### ISSUE TITLE
TCC and Tera proxy

### ISSUE THREAD

**Issue by Drufisto** [Foglio1024/Tera-custom-cooldowns#147]
Im not sure if its just me but when i try to run both TCC and tera proxy, TCC will open but the overlays will not be shown ingame is this a bug or are the programs just not compatible?

**Comment by Foglio1024** [comment]
I don't think it's related to tera-proxy, unless it's configured in some weird way that messes up with connection detection. Also TCC uses proxy for some features via tcc-stub module, so no, there's no compatibility issue.

**Comment by Drufisto** [comment]
I redownloaded TCC just in case and this is what i have in tera proxy and for some reason its not loading the TCC master even though i have it unless it doesnt belong there 
![shiet](https://user-images.githubusercontent.com/39699199/40621522-124c7538-626b-11e8-8f31-f6a711ab91a9.PNG)
![i need a hero](https://user-images.githubusercontent.com/39699199/40621555-446f4a04-626b-11e8-8afa-48cebdd863c4.PNG)

**Comment by Foglio1024** [comment]
TCC is not a proxy module, it's a standalone application. It uses tcc-stub for communication with proxy for advanced functionalities.

**Comment by Drufisto** [comment]
So just delete both tcc-stub and tcc master?

**Comment by Foglio1024** [comment]
Just delete TCC master.

**Comment by Drufisto** [comment]
I have no idea why it doesnt show on my game even re-downloaded TCC and erased the TCC master and still the overlays dont show on my game

**Comment by Foglio1024** [comment]
Make sure you followed setup instructions correctly.

**Comment by Drufisto** [comment]
Is there like a step by step TCC and Tera proxy setup that i can follow?

**Comment by Gl0** [comment]
https://foglio1024.github.io/Tera-custom-cooldowns/

**Comment by Drufisto** [comment]
Thanks for that and can you combine TCC, Tera proxy and WTFast together if so how can you do it?
