### ISSUE TITLE
Windows 8 unable to update/start new version of TCC

### ISSUE THREAD

**Issue by Giraffno** [Foglio1024/Tera-custom-cooldowns#151]
To open the TCC is needed .NET Framework 4.7.1 but windows 8 can't download it (while 8.1 can).
Is it possible to do something about this?

**Comment by Foglio1024** [comment]
You could check [this issue](https://github.com/Foglio1024/Tera-custom-cooldowns/issues/173#issuecomment-414389074) and see if it works, else the best solution would be tu upgrade to Windows 10.
