### ISSUE TITLE
Issue with 'application info window'

### ISSUE THREAD

**Issue by jovan-pavlovic** [Foglio1024/Tera-custom-cooldowns#154]
![qwe](https://user-images.githubusercontent.com/38740901/42412176-616b4bb0-8207-11e8-804f-b328bb7a684e.png)
This window keeps popping up on its own,i even disabled it in _S1UI,still keeps popping up but not showing this window(it looks like when you press ESC to move mouse around screen).It doesnt pop up when i start game without tcc.

**Comment by Foglio1024** [comment]
https://github.com/Foglio1024/Tera-custom-cooldowns/wiki/Ingame-UI-removal 3rd row of the table.

**Comment by jovan-pavlovic** [comment]
have everything from that table in s1ui still popping

**Comment by Foglio1024** [comment]
That's `S1UI_PartyWindowRaidInfo.gpk`, it's in that table's 3rd row.

**Comment by Foglio1024** [comment]
Oops, wrong row. I mean last one: `S1UI_PartyBoardMemberInfo.gpk`.

**Comment by jovan-pavlovic** [comment]
every gpk file,still keeps popping,i do have some other gpk files if that matters,heres list 
![qwe](https://user-images.githubusercontent.com/38740901/42416193-4267eda2-8268-11e8-98e7-18c626fabe09.png)
