### ISSUE TITLE
TCC crashs in KR server

### ISSUE THREAD

**Issue by concert2011** [Foglio1024/Tera-custom-cooldowns#155]
##### CRASH #####
호출 대상이 예외를 Throw했습니다.
   위치: System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   위치: System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   위치: System.Delegate.DynamicInvokeImpl(Object[] args)
   위치: TCC.Parsing.MessageFactory.Instantiate(UInt16 opCode, TeraMessageReader reader) 파일 D:\Repos\TCC\TCC.Core\Parsing\MessageFactory.cs:줄 292
   위치: TCC.Parsing.PacketProcessor.PacketAnalysisLoop() 파일 D:\Repos\TCC\TCC.Core\Parsing\PacketRouter.cs:줄 86
   위치: System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   위치: System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   위치: System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   위치: System.Threading.ThreadHelper.ThreadStart()
mscorlib
System.Reflection.TargetInvocationException: 호출 대상이 예외를 Throw했습니다. ---> System.IO.EndOfStreamException: 스트림의 끝을 넘어 읽을 수 없습니다.
   위치: System.IO.__Error.EndOfFile()
   위치: System.IO.MemoryStream.InternalReadInt32()
   위치: TCC.Parsing.Messages.S_USER_EFFECT..ctor(TeraMessageReader reader) 파일 D:\Repos\TCC\TCC.Core\Parsing\Messages\S_USER_EFFECT.cs:줄 31
   위치: lambda_method(Closure , TeraMessageReader )
   --- 내부 예외 스택 추적의 끝 ---
   위치: System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   위치: System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   위치: System.Delegate.DynamicInvokeImpl(Object[] args)
   위치: TCC.Parsing.MessageFactory.Instantiate(UInt16 opCode, TeraMessageReader reader) 파일 D:\Repos\TCC\TCC.Core\Parsing\MessageFactory.cs:줄 292
   위치: TCC.Parsing.PacketProcessor.PacketAnalysisLoop() 파일 D:\Repos\TCC\TCC.Core\Parsing\PacketRouter.cs:줄 86
   위치: System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   위치: System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   위치: System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   위치: System.Threading.ThreadHelper.ThreadStart()
System.Collections.ListDictionaryInternal
System.IO.EndOfStreamException: 스트림의 끝을 넘어 읽을 수 없습니다.
   위치: System.IO.__Error.EndOfFile()
   위치: System.IO.MemoryStream.InternalReadInt32()
   위치: TCC.Parsing.Messages.S_USER_EFFECT..ctor(TeraMessageReader reader) 파일 D:\Repos\TCC\TCC.Core\Parsing\Messages\S_USER_EFFECT.cs:줄 31
   위치: lambda_method(Closure , TeraMessageReader )
System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)

**Comment by Foglio1024** [comment]
TCC is not updated for new KR patch yet.
