### ISSUE TITLE
TCC and OBS (as of 2.1.2 obs x64 update)

### ISSUE THREAD

**Issue by Reny900** [Foglio1024/Tera-custom-cooldowns#157]
I've read the guides about how to capture TCC with OBS and none of them are working, while Shinra, after the false in the window.xml for the transparency, is showing.
I'm currently running win7 with a 1060 6 GB (EVGA) graphic cards, any idea?

**Comment by Reny900** [comment]
seems like re-enabling some options inside this [https://i.imgur.com/LJG7Fu4.png](menù) have fixed the problem

**Comment by Foglio1024** [comment]
The only way to stream TCC is with screen capture mode, as stated in the FAQs. Good to know that these settings can help avoid issues.
