### ISSUE TITLE
Combat Chat

### ISSUE THREAD

**Issue by nibewiahn** [Foglio1024/Tera-custom-cooldowns#160]
Is there a way to add a combat chat? I cant find any option to select the combat damage info on tcc.

**Comment by Foglio1024** [comment]
It wasn't included on purpose. I may only add damage received by the user in the future.

**Comment by nibewiahn** [comment]
Is there a way aroundthat? i was thinking about remove the S1UI_Chat2.gpk and Use a Blank orinal chat under the tcc and add a tab for the combat maybe? But than I would get a pesky event notice on top of the original chat!

**Comment by Foglio1024** [comment]
You are forced to use modded S1UI_Chat2.gpk, or TCC won't be able to communicate with game and any form of interaction wouldn't be possible.

**Comment by nibewiahn** [comment]
Got it, Thx!!! I ill wait patiently!!! Keep up with the awesome work!!!

**Comment by nibewiahn** [comment]
Is the opacity adjust gone ???????????And what is the minimize option?

**Comment by nibewiahn** [comment]
![image](https://user-images.githubusercontent.com/20910450/43958098-9e127442-9c80-11e8-82f6-421ae1ef9bfb.png)

1.1.1 Even with 0 opacity I can still see it!

**Comment by Foglio1024** [comment]
Yeah, the "glass" border is "fixed". Only the dark background can be made opaque to read better.

**Comment by nibewiahn** [comment]
Is it possible to make the timestamp and channel hide/remove per channel?? I mean we dont need that on the dmg channel

**Comment by Foglio1024** [comment]
No, that's a global setting.

**Comment by nibewiahn** [comment]
Would be too hard to make it per window?

**Comment by Foglio1024** [comment]
It wouldn't be worth the effort, imo.
