### ISSUE TITLE
Hide party leader options for non-leaders

### ISSUE THREAD

**Issue by scarfcat** [Foglio1024/Tera-custom-cooldowns#162]
Hi, a suggestion I'd love to see implemented is to hide the leader options since they are always displayed in the group window. It confuses the hell out of me, and I sometimes change loot options and fuck it all up because I'm not the leader.

**Comment by Foglio1024** [comment]
That's actually not supposed to be showed if you're not leader. So that's most probably a bug occurring when passing lead or something.

**Comment by scarfcat** [comment]
Hmm okay, Any logs or something I can post to help debug this? Because they're always there for me. I had my friend invite me to party, and the leader options were displayed even though I was never the leader in that party.

**Comment by Foglio1024** [comment]
You could post your settings. Probably some disabled window is interfering with leader change notification.

**Comment by scarfcat** [comment]
Screenshot or a file i can upload?

**Comment by Foglio1024** [comment]
tcc-config.xml

**Comment by scarfcat** [comment]
attached

**Comment by scarfcat** [comment]
txt because for some reason github doesn't support xml

[tcc-config.xml.txt](https://github.com/Foglio1024/Tera-custom-cooldowns/files/2270522/tcc-config.xml.txt)
