### ISSUE TITLE
missing cooldowns

### ISSUE THREAD

**Issue by crvN** [Foglio1024/Tera-custom-cooldowns#17]
on my ninja, when i non-stop use skills some of them (Chakra Thrust, One Thousand Cuts most of all) are missing in cooldown list

**Comment by Foglio1024** [comment]
It was a known issue, then i fixed it, but after switching to new database it probably broke. I'll look into it.

**Comment by Foglio1024** [comment]
Fixed in abc1165bfaeaefde77fbb1def3633aaaa36457c1
