### ISSUE TITLE
Can't Run TCC

### ISSUE THREAD

**Issue by Kukharevich** [Foglio1024/Tera-custom-cooldowns#173]
TCC crashes just right after the running
![image](https://user-images.githubusercontent.com/42327712/44282456-d0012c80-a263-11e8-8854-49c8a8428bd2.png)
Region: RU
If there's anything you need me to translate or/and give you more info (and where I can get it), please let me know, Thanks

**Comment by Foglio1024** [comment]
Try installing .NET 4.7.2 manually.

**Comment by Kukharevich** [comment]
> Try installing .NET 4.7.2 manually.
I did. Still the same

**Comment by Kukharevich** [comment]
>

**Comment by Kukharevich** [comment]
Oops, missclicked

**Comment by Foglio1024** [comment]
From the FAQs on discord: `You need to install kb 4076492 from windows update`

**Comment by Kukharevich** [comment]
For 2 days, in my free time I've been trying to install it but I cant. It just keeps sending me the same error. I feel like I've tried everything, but all of this wasn't very effective. I downloaded and tried to install all of this:
![image](https://user-images.githubusercontent.com/42327712/44343701-59e50b80-a497-11e8-9d86-ba8e576243a2.png)
But still, I have "The KB4076492 software update installation wizard does not work or is blocked by another condition on your computer" and that's it.

**Comment by Gl0** [comment]
try uninstalling all dotnet 4.7+ with https://blogs.msdn.microsoft.com/astebner/2008/08/28/net-framework-cleanup-tool-users-guide/ , reboot, reinstall from direct download links and then polish result with windows update.

**Comment by Kukharevich** [comment]
Nothing really happened. KB4076492 still sends me the same error. I tried to install KB4345679 (at least, it installed) but that didn't change anything

**Comment by Gl0** [comment]
KB4076492 is for .net 4.7.1, 4.7.2 should already include fixes from this kb. 
if you still getting that error - something broken in your windows installation more deeply. Easiest solution - reinstall windows from original MS ISO.

**Comment by Kukharevich** [comment]
Well, thats a little bit too deep. I have no will to reinstall windows for just TCC. Anyway, huge thanks to both of you, guys. I hope that'll help someone with the same problem.

**Comment by Gl0** [comment]
that's not just TCC problems, You'll probably encounter same error in other .net programs
