### ISSUE TITLE
New functionality

### ISSUE THREAD

**Issue by lofuy** [Foglio1024/Tera-custom-cooldowns#175]
I propose that functionality:  create a profile for each chara we have or the tcc adapt himself when you logon the chara. what i mean is when you logon the tcc the life bar place him self at the right place but with the skill bar and cooldown bar we have to place it each time we logon on a chara if he is a other class than the previous. I know it may be difficult to realise. thanks for the development :)

**Comment by Foglio1024** [comment]
Done in v1.1.8
