### ISSUE TITLE
pet hunger status

### ISSUE THREAD

**Issue by nibewiahn** [Foglio1024/Tera-custom-cooldowns#176]
IS there a way to add a small icon for pet hunger status on chatacter hp/mp bar (like equip lvl) or somewhere else???
Something like this:
![image](https://user-images.githubusercontent.com/20910450/44310016-e6af9c80-a3a5-11e8-99da-dc02474099a5.png)
but smaller, thx mate!

Keep UP with the good work, the NEW class icons are amazing!!!

**Comment by Foglio1024** [comment]
I'll look into it, it probably needs different packet definitions which are not released at the moment.

**Comment by nibewiahn** [comment]
THX!!!
