### ISSUE TITLE
Priest awakening skills cooldowns

### ISSUE THREAD

**Issue by RokkuBando** [Foglio1024/Tera-custom-cooldowns#179]
![tcc](https://user-images.githubusercontent.com/22872026/44765780-017cd080-ab5f-11e8-82a5-4e4bc8838789.jpg)

The new skills cooldowns don't show on the TCC cooldowns panel :) 
But this is so much needed once you start getting used to this neat addition.

**Comment by Foglio1024** [comment]
Divine Charge is not triggered because it's already present in class window. Holy Burst may bug out sometimes like all other skills.

**Comment by Foglio1024** [comment]
Also, I just found the issue about Holy Burst, it will be fixed in next release.

**Comment by Foglio1024** [comment]
It doesen't refer to all classes. Class window shows most important skills for your class, so there's no point in showing them as duplicate in cd bar imo. If you want to see them in cd bar you can disable class window (since priest one only contains skills cooldowns).
