### ISSUE TITLE
Crash on version 0.1.6

### ISSUE THREAD

**Issue by futa** [Foglio1024/Tera-custom-cooldowns#18]
Thanks for this awesome mod! Occasionally, I am crashing when logging in. Please see the attached log.
[error.txt](https://github.com/Foglio1024/Tera-custom-cooldowns/files/946265/error.txt)

**Comment by Foglio1024** [comment]
Kinda weird error. Should be fixed with 8068ded1ef6f6ef64050e1a5629e94a5742c71d9.

**Comment by electronicc** [comment]
Sorry about my English
I could give an opinion ?
Can you add distance in the application?
example
Show distance from boss
I play with Ctrl + z 
That's why I do not see the distance.
google tradutor
Very ty man

**Comment by electronicc** [comment]
exmple
Playing normal
http://prntscr.com/ez2ltg


Playing with Ctrl + z
http://prntscr.com/ez2n6n

No distance from idea

**Comment by Foglio1024** [comment]
That would require a lot of work calculating positions from location packets and it would not update fast. Ingame distance is done by game engine and there's no network data related to it.

**Comment by electronicc** [comment]
Okay, thanks for the quick response.

**Comment by futa** [comment]
Looking great! No crashes so far today!

**Comment by futa** [comment]
Forgot to add, thank you so much!
