### ISSUE TITLE
TCC Boss Bar

### ISSUE THREAD

**Issue by JohnSno69** [Foglio1024/Tera-custom-cooldowns#188]
The boss bar is working fine except for one issue, if its an issue...TERA's original boss bar still shows up. Is it supposed to hide with TCC boss bar, or do i have to tuck it away in a corner.

If it supposed to hide with the TCC boss bar, then please help with that.

If its not supposed to hide, how can I?

**Comment by Foglio1024** [comment]
https://github.com/Foglio1024/Tera-custom-cooldowns/wiki/Ingame-UI-removal

**Comment by JohnSno69** [comment]
Thanks it worked. But one more thing though. Is there a way to remove the words in blue that pop up in the center of the screen. Tera has an option for it, but its not working/never worked. Is there a way to hide those too?

**Comment by Mister-Kay** [comment]
Yes. You can either use:

The datacenter mod by pinkie pie from their discord: [Link](https://discord.gg/RR9zf85) (in the `#client_mods` channel)

Or the gpk mod by Owyn from Essential Mana: [Link](https://www.essentialmana.com/forums/#/discussion/7268/owyns-ui-mods-awakening-update) (it's labelled "Disable Messages in the center of the screen + Transparent background")

**Comment by Foglio1024** [comment]
You could also use `S1UI_Message.gpk` from patch 75 client; it has some visual bugs (some texts are displayed as squares, fonts is a bit small, dungeon messages disappear too quickly). but it's way cleaner than current one.

Western regions will get it in about a month without those bugs.
