### ISSUE TITLE
Lancer skill cooltime problem

### ISSUE THREAD

**Issue by concert2011** [Foglio1024/Tera-custom-cooldowns#197]
in ClassSpecific\LancerAbnormalityTracker.cs

    public class LancerAbnormalityTracker : ClassAbnormalityTracker
    {
        //private static readonly uint[] ARushIDs = { 200700, 200701, 200731, 200732 };
        private static readonly uint[] ARushIDs = { 200700, 200701, 200731 };
        ....
    }

Please remove 200732 from ARushIDs. It cause a problem with talent system in KR.

**Comment by Foglio1024** [comment]
Fixed in v1.1.33.
