### ISSUE TITLE
Removing some UI Elements

### ISSUE THREAD

**Issue by samtera** [Foglio1024/Tera-custom-cooldowns#2]
Big fan of the UI however I'd like to remove the HP bar UI overlay and keep the current one I have. How can I go about doing this?

Thanks.

**Comment by Foglio1024** [comment]
It's still not possible at the moment. It will be added as option together with other features in a dedicated "Settings" window.

**Comment by samtera** [comment]
Sweet, I look forward to it!

**Comment by Foglio1024** [comment]
Option added to disable UI elements in v0.1.1.
