### ISSUE TITLE
Priest class bar 

### ISSUE THREAD

**Issue by f3ck4r** [Foglio1024/Tera-custom-cooldowns#207]
Is there a way to make the priest class bar like this?
![unknown](https://user-images.githubusercontent.com/26763836/48983063-5df57a80-f0d1-11e8-907f-5378b69d6cd2.png)

**Comment by totallynotmandy** [comment]
Is there a way to even customize the class bar

**Comment by Foglio1024** [comment]
There's no way to customize class bars at the moment. Only warrior one has some settings. I can take suggestions and add some settings for them though.

**Comment by totallynotmandy** [comment]
I just really want tornado to be on the priest class bar as well because that is something that needs to be spammed off cd

**Comment by Foglio1024** [comment]
I don't think I'm going to put damage skills in class windows anyway, even if they're spammed off cd.

**Comment by totallynotmandy** [comment]
it's not used for damage though, it's the awakened passive that lets priests farm their Edict of Judgement back and so they can have it up every enrage. Regardless, I guess it's okay if it's not on there, I'll just stick to the CD bar.
