### ISSUE TITLE
Skills shortcut hotkeys messed up.

### ISSUE THREAD

**Issue by mckenzieboo** [Foglio1024/Tera-custom-cooldowns#223]
Hello, 

My skills bars got completely messed up after installing. Everything else is just perfectly fine, except the skills shortcuts bars.
They are HUGE and the extra shortcut tray is one skill over the other.
Please.. help :(

**Comment by Foglio1024** [comment]
Can you provide a screenshot, please?

**Comment by mckenzieboo** [comment]
Sure,
Sorry about the link I don't know how to insert images.
http://i65.tinypic.com/10xevsz.png

Thanks for amazing fast response.

**Comment by Foglio1024** [comment]
You have a modded `main` skill bar coming from patch 75, that's probably causing the issue.

**Comment by mckenzieboo** [comment]
What does that mean? is there a way to fix it?

**Comment by Foglio1024** [comment]
You installed a modded main skill bar (probably to remove the darker border) which is based on old UI. If you installed it the "right" way you should have an `_S1UI` folder with modded files somewhere in your TERA folder, else - if you overwrote the original file from `S1UI` folder -  you'll need to find a clean `S1UI_TestQuickSlot.gpk` and place it in `TERA\Client\S1Game\CookedPC\Art_Data\Packages\S1UI`.

**Comment by mckenzieboo** [comment]
mm.. I don't really know because I share the computer with my husband, but I know for a fact that the _S1U1 doesn't not have mods bc I created it exclusively for TCC. I will try to do it on the main file. 
Thanks for the help and fast response.

**Comment by mckenzieboo** [comment]
... I did as recommended and it is still the same. 
For the _S1UI files, for TCC, I used the compact files found on a video from 2017. Those are the only files I have there - see link.
http://i63.tinypic.com/2rcbhug.png

**Comment by Foglio1024** [comment]
Try removing those and follow [this page](https://github.com/Foglio1024/Tera-custom-cooldowns/wiki/Ingame-UI-removal)  for gpk mods related to TCC.

**Comment by mckenzieboo** [comment]
Okay, i just did it, the extra shortcut is back to normal.... but the other shortcut trays... disappeared and the one provided from TCC didn't appear.
See link.
http://i64.tinypic.com/30atkih.png

I'm sorry about all this trouble.. T_T I have no idea why this is happening...
