### ISSUE TITLE
Scythe

### ISSUE THREAD

**Issue by kaiken24** [Foglio1024/Tera-custom-cooldowns#225]
some times playing as a wr, in my colldown bar appears skills called Scythe II, Scythe V and Scythe IX with no colldown time(my bar its in normal mode), and no matter how many times i exclue then in hidden skills then stiil comming up

**Comment by Foglio1024** [comment]
I thought that was fixed some versions ago. Try using 1.3.X if you're not using it already.

**Comment by kaiken24** [comment]
im using the 1.38

**Comment by Foglio1024** [comment]
Fixed in 1.3.9-e
