### ISSUE TITLE
Valk class window, Timer on ragnarok broken

### ISSUE THREAD

**Issue by MaDgiKCoOkie** [Foglio1024/Tera-custom-cooldowns#229]
Hello, 

As I mentioned in the title, the class window doesnt show the remaining time of Ragnarok anymore, only 0. The buff window is working fine, and show correct timer left.

It hasnt been working almost since awakening, and I thought it was already known.

Thank you

**Comment by Foglio1024** [comment]
I know the issue but I always forget to fix it, since I'm not playing valk lately. Also I actually wanted to remake valk class window from scratch, that's why I kinda postponed it.

Thanks for the report anyway, it will be fixed soon ™️

**Comment by MaDgiKCoOkie** [comment]
Thanks a lot for your work :)

**Comment by Foglio1024** [comment]
Keeping this open as reminder.

**Comment by Foglio1024** [comment]
Fixed in next release
