### ISSUE TITLE
How to use??

### ISSUE THREAD

**Issue by andersonepk** [Foglio1024/Tera-custom-cooldowns#239]
I m using but nothing changed, i m missing something??
Is caali proxy
![image](https://user-images.githubusercontent.com/18029568/59283504-1388b500-8c41-11e9-8d7b-c1d5f0f6f799.png)
Thanks

**Comment by Foglio1024** [comment]
TCC is not a Toolbox module (yet). You have to download latest release from [here](https://github.com/Foglio1024/Tera-custom-cooldowns/releases), extract and run it as a separate application. Then, after completing other installation steps, you can install tcc-stub from Toolbox's "Get More Mods" tab to enable TCC-Toolbox communication and advanced features.

**Comment by andersonepk** [comment]
So i did it now, donwload then install, open proxy and active 
I still need open the TCC.exe 
![image](https://user-images.githubusercontent.com/18029568/59289502-982d0080-8c4c-11e9-9cbc-42e5f21a44bb.png) or it will now run with proxy??

Or i have to open TCC then proxy?

I Cant test now cause game in maintence ¬¬

![image](https://user-images.githubusercontent.com/18029568/59289450-7cc1f580-8c4c-11e9-9491-f0fc6fb2d50c.png)

**Comment by andersonepk** [comment]
well, i still need open TCC.exe to run with tera, its ok.

there is alot things we can configure with this tool, its is nice...
there is any guide or document of functions this mod to share?

thanks
