### ISSUE TITLE
Error Reading Characters.xml

### ISSUE THREAD

**Issue by Malcheczar** [Foglio1024/Tera-custom-cooldowns#240]
Hello, I am new to this tool and was trying to set it up when I get "There was an error while reading characters.xml. Manually correct the error and press Ok to try again, else press Cancel to delete current data." and cannot go past this.  As far as I can tell there isn't a characters.xml anywhere in the directory so I'm not sure how to proceed.  Any help would be appreciated.

![image](https://user-images.githubusercontent.com/52358782/60388558-02310c80-9a79-11e9-915b-bbec15abe750.png)

[crash.log](https://github.com/Foglio1024/Tera-custom-cooldowns/files/3342239/crash.log)

**Comment by Malcheczar** [comment]
@Foglio1024

**Comment by Foglio1024** [comment]
This won't make things faster :^)

**Comment by Malcheczar** [comment]
Just wanted to make sure it was seen. thats all :P

**Comment by Malcheczar** [comment]
Any update/ideas for this? I'd like to start using this mod but it doesn't look like I can until this is sorted.  Thanks for your hard work Foglio.

**Comment by Malcheczar** [comment]
Looks like this error has been fixed in one of your recent versions, thanks!
