### ISSUE TITLE
Priest class window icons

### ISSUE THREAD

**Issue by 542673** [Foglio1024/Tera-custom-cooldowns#243]
Priest class window is currently missing icons, although i already updated icons by confirming the popup un startup 
![priestclasswindow](https://user-images.githubusercontent.com/46850988/62631970-f6671e80-b931-11e9-80b3-2b323ed81ddc.png)

**Comment by Foglio1024** [comment]
Refer to https://github.com/Foglio1024/Tera-custom-cooldowns/wiki#manual-icon-database-download for manual icon download.
