### ISSUE TITLE
TCC crash 4k monitor

### ISSUE THREAD

**Issue by dimitrykostin** [Foglio1024/Tera-custom-cooldowns#247]
Hi!

I have 2 monitors.
Tera run on 4k window mode on windows 10 64 bit.
At first run is ok. At second run TCC crashed. If i delete config, TCC start but settings reset.

[tcc-config.xml.txt](https://github.com/Foglio1024/Tera-custom-cooldowns/files/4015223/tcc-config.xml.txt)
[crash.log](https://github.com/Foglio1024/Tera-custom-cooldowns/files/4015210/crash.log)

**Comment by Foglio1024** [comment]
It should work properly in v1.4.X
