### ISSUE TITLE
Return enrage timer

### ISSUE THREAD

**Issue by webstersama** [Foglio1024/Tera-custom-cooldowns#25]
Its one one best things in TCC. Very useful. Pls return this.

**Comment by Foglio1024** [comment]
I didn't remove it. It's been moved under the yellow arrow. It displays time left instead of percentage, when boss is enraged.

**Comment by webstersama** [comment]
I know, just big icon looks better. Timer under bar too small. And Its more time for get information in battle.

**Comment by webstersama** [comment]
Dont binding timer to boss HP. Pls, make it like early.

**Comment by LaraNotsil** [comment]
+1 big face at the right was better, but timing is needed too

**Comment by Foglio1024** [comment]
I'm reworking pretty much all windows. I'll see if I can come up with some nice design when I'll start reworking boss bar.

**Comment by webstersama** [comment]
1st design was nice. If u want, u can make few themes but save default pls.

**Comment by Frostypeaches** [comment]
+1 vote to bring back the giant red face.

**Comment by Foglio1024** [comment]
Enrage timer kinda returned in different way, closing this.
