### ISSUE TITLE
asking repeatedly to install net.core, tcc won't work

### ISSUE THREAD

**Issue by lidel97** [Foglio1024/Tera-custom-cooldowns#255]
hi, everytime i open tcc, application says that needs net.core , i also tried to install both versions for windows ( 64 and 32 bit) but it won't work and everytime i open tcc, it always shows me that needs net.core. i tried to do a fresh installation, it won't work

**Comment by Foglio1024** [comment]
You need to install the correct package - x64 Desktop Runtime: https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-desktop-3.1.5-windows-x64-installer

**Comment by lidel97** [comment]
ok, thank you very much. gonna try and then i'll write here if it's worked.

**Comment by lidel97** [comment]
now it works! thanx again, cya!
