### ISSUE TITLE
No Boss Bar in Velik's Sanctuary

### ISSUE THREAD

**Issue by Frostypeaches** [Foglio1024/Tera-custom-cooldowns#29]
as title says, the bosses in this dungeon don't produce a TCC boss bar.

**Comment by Foglio1024** [comment]
If you play on NA, you're probably missing the monsters database, which I didn't update yet. If you use Shinra meter you can just copy it from {ShinraMeter folder}\resources\data\monsters into your {TCC folder}\resources\data\monsters.
