### ISSUE TITLE
Integrate translation in chat

### ISSUE THREAD

**Issue by foglio1024** [foglio1024/tera-custom-cooldowns#319]
- https://codelabs.developers.google.com/codelabs/cloud-translation-csharp#0
- https://github.com/tera-classic-mods/translate-chat
- https://stackoverflow.com/questions/1192768/how-to-detect-the-language-of-a-string/1192802#1192802
- https://github.com/ivanakcheurov/ntextcat

**Comment by Foglio1024** [comment]
Consider just adding support for the existing translation mod. This implies the following steps:
- [ ] Add support for fake packets to external-interface (see https://github.com/Foglio1024/external-interface/issues/1)
- [ ] Detect translated messages (by `(Translated)` prefix? Kinda weak, but probably the only way without modifying the `translate-chat` mod)


**Alternatively:**
- [ ] Only hook fake `S_CHAT` with the `(Translated)` prefix like it's done with `S_PRIVATE_CHAT` in [tcc-stub](https://github.com/Foglio1024/Tera-custom-cooldowns/blob/master/TCC.Core/Module/network/tcc-stub.js#L103)
- [ ] In TCC, merge the translation message with the original message
   - [ ] Consider caching in case the order of arrival is reversed 
   - [ ] Consider a setting to configure the default displayed version of the message (translated first or original first)
   - [ ] Add a translation icon next to the translated message: hovering/clicking the icon will display the translated/original message (or just toggle) depending on the setting

**Comment by foglio1024** [comment]
Done in https://github.com/foglio1024/tera-custom-cooldowns/releases/tag/v1.4.156
