### ISSUE TITLE
Tcc can sometimes disappear

### ISSUE THREAD

**Issue by Reny900** [Foglio1024/Tera-custom-cooldowns#32]
Long story short. When i press alt (to make the mouse con visible), and then proceed to click things on my other monitor, it may happen that the all the windows shown by TCC could disappear. 
Just made a Velik Hold Normal mode, in Veteran mode, No health bar, no cooldwons, no Raid window ...

**Comment by Foglio1024** [comment]
Fixed in 5112b976bd495d4c1553c1c62e6bf494e1a7ce8c. I'll upload binaries later. You can temporarily fix it by opening TCC settings and turn visibility off and back on for each window.
