### ISSUE TITLE
App crashes on NA

### ISSUE THREAD

**Issue by kivelz** [Foglio1024/Tera-custom-cooldowns#33]
in 0.41 ver tcc crashes, in 0.40 its not working somehow for some people

**Comment by Foglio1024** [comment]
Send me error.txt when reporting crashes, please

**Comment by kivelz** [comment]
[error.txt](https://github.com/Foglio1024/Tera-custom-cooldowns/files/1006571/error.txt)

**Comment by Foglio1024** [comment]
Ok, seems like it didn't recognize your Tera version. Do you use proxy/vpn?

**Comment by kivelz** [comment]
yes i use proxy and wtfast

**Comment by Foglio1024** [comment]
Ok, I'll add server override support like Shinra in next release.

**Comment by kivelz** [comment]
okie thank you so much!

**Comment by Foglio1024** [comment]
Fixed in 795cdee4c963d1131354639a48624cab1030af16.
