### ISSUE TITLE
bam

### ISSUE THREAD

**Issue by mohed12** [Foglio1024/Tera-custom-cooldowns#34]
bam hp like in IoD not work

**Comment by Foglio1024** [comment]
I have removed that for now. Only bosses with ingame HP bar are showed.

**Comment by mohed12** [comment]
why bro was fun 
any chance u will add key for it to be on ?

**Comment by Foglio1024** [comment]
Maybe I'll make a setting for it. I removed it because it caused major lag when too many mobs were around.

**Comment by mohed12** [comment]
ty gl
