### ISSUE TITLE
Hard CPU loading

### ISSUE THREAD

**Issue by webstersama** [Foglio1024/Tera-custom-cooldowns#39]
Hello. Have problem with lags while last version TCC started.
I seen this problem only on my core i5 CPU's. On core i7 i dont have lags.

**Comment by webstersama** [comment]
I turned on only boss bar.

**Comment by Foglio1024** [comment]
I can't fix this since I've received only few reports about this and I can't reproduce the issue myself to look into it. If it causes big issues you can always lower TCC priority using task manager.

Note: high CPU load is normal, specially in situations like guild/event bams.

**Comment by Foglio1024** [comment]
Fixed in 0.4.5
