### ISSUE TITLE
Hp Bar Color

### ISSUE THREAD

**Issue by SpackU** [Foglio1024/Tera-custom-cooldowns#42]
Hey, can you add a feature to HP bar to change color to purple when you get a bleed effect?

**Comment by Foglio1024** [comment]
If you talk about your HP bar, it should already work. 

Party members' purple bars will come later.

**Comment by mohed12** [comment]
i was think about this it will be nice to add some thing for bad effect

**Comment by SpackU** [comment]
it's not purple for me...

**Comment by Foglio1024** [comment]
Ok, I just checked and seems like it's broken now. I didn't notice before because I don't use that bar (I was actually planning to remove it, since it doesen't really add any extra functionality and also decreases overall TCC smoothness).
