### ISSUE TITLE
0.43 error with VPN

### ISSUE THREAD

**Issue by kivelz** [Foglio1024/Tera-custom-cooldowns#43]
tried it with vpn teracooldown crashed though
[error.txt](https://github.com/Foglio1024/Tera-custom-cooldowns/files/1014632/error.txt)

**Comment by Foglio1024** [comment]
Did you add VPN entry in server-overrides.txt? It works the same way as ShinraMeter.

**Comment by kivelz** [comment]
erm do u have a link on how i can do that? i have no issue with shinra though

**Comment by Gl0** [comment]
@Foglio1024 in shinra you don't need to add anything in most cases.
You should init DB on S_Login, not on server connect for configless VPN support.

**Comment by Foglio1024** [comment]
@Gl0 ok, I'll try in that way.

@kivelz You can try doing this as a temporary fix https://github.com/neowutran/ShinraMeter/wiki#vpnproxy.

**Comment by kivelz** [comment]
k works but then another error xd
[error.txt](https://github.com/Foglio1024/Tera-custom-cooldowns/files/1015950/error.txt)

**Comment by Daren02** [comment]
Im sorry for this stupid and noob question but.. I cant see where I have to open the app, i mean, theres one that is call "App" but it just open my browser and say error. I tried to open it with CMD.exe but nothing, Can someone help me please? Sorry u.u
