### ISSUE TITLE
TCC not working

### ISSUE THREAD

**Issue by codexINSANITY** [Foglio1024/Tera-custom-cooldowns#48]
Somehow it's doing nothing forme expect putting the TTC settings into my sys tray.
Shinra seems to work, but TCC doesn't even want to create the character skill xml file for me.
Any idea what i'm doing wrong?

**Comment by Foglio1024** [comment]
Check that you did everything in the requirements (same as Shinra, so I guess you did that already) https://github.com/neowutran/ShinraMeter/wiki#prerequisite. I had another person with the same issue, but we couldn't figure out what was wrong.

**Comment by codexINSANITY** [comment]
Any information i can pass you on?

**Comment by Foglio1024** [comment]
You can check if you have any error.txt in TCC folder and send it to me.

**Comment by codexINSANITY** [comment]
[error.txt](https://github.com/Foglio1024/Tera-custom-cooldowns/files/1032127/error.txt)
here you go

**Comment by Foglio1024** [comment]
Ok so, that's the error which occurs randomly when opening TCC. I haven't figured out why it happens yet. When it happens, the application shuts down without removing tray icon (you can check it by hovering mouse on it - if it disappears it means TCC crashed). It doesen't happen everytime, so make sure that TCC is actually running by checking tray icon (I will add a message to warn the user that an error occured), then try running it again.

Also, xml files are generated when logging in a specific class for the first time.

**Comment by codexINSANITY** [comment]
I just tried it again and it seems like that error occured maybe once without me even noticing.
I can open the the TCC settings from the try without it giving me any kind of error.
There is no way that a dual monitor setup is fucking that up in any way or is it? 
Im also playing in Fullscreen ( Windowed) but also tried just windowed but still nothing.
at this point im not sure if I'm fucking something up.

**Comment by Foglio1024** [comment]
Does icon turn green after you connect to server?

**Comment by codexINSANITY** [comment]
nope it stays red

**Comment by Foglio1024** [comment]
Then I don't know where the problem is. Maybe some antivirus or something blocking it?

**Comment by codexINSANITY** [comment]
Turning winpcap from true to false in the windows.xml file unter reources/config and adding a rule to the firewall helped.
Thanks again!
