### ISSUE TITLE
TCC Not Connecting with WTFast & Tera-Proxy

### ISSUE THREAD

**Issue by Eng-RedWolf** [Foglio1024/Tera-custom-cooldowns#49]
**First Great Work on the TCC im really loving it.**
One problem tho **TCC** is not working when i have **WTFast** and **Proxy** on, however **Shinrameter** its working fine, but **TCC** is not connecting at all when i have them on, i know both of **Shinrameter** and **TCC** share the same programing, and i have both with the same setup and config file.

**Comment by Foglio1024** [comment]
Sorry for answering late, I've been busy last days. 

I'm not sure what could be causing your problem, since you seem to have done everything already. The only thing I could suggest is to check firewall rule for TCC and make sure that winpcap is set to false in TCC window.xml file.
