### ISSUE TITLE
Can not scale the new cooldown bar

### ISSUE THREAD

**Issue by Sohalee** [Foglio1024/Tera-custom-cooldowns#50]
Hi Foglio,
I am really appreciate for your great job at making this awesome plugin for Tera.
But i am having an issue with the TCC v0.5 since i can not scale the new cooldown bar to sizes. in v0.4.9 everything was fine, i can scale the new cooldown bar by scale down the class window settings but now they don't attach to each other anymore. Or am i missing something ?

Thank you for your support.

**Comment by Foglio1024** [comment]
I think I forgot to check the scale settings after detaching the window. I'll release a fix together with EU update in few hours.

**Comment by Foglio1024** [comment]
Fixed in e9100c702d79d3d532e967640459c5f9c6472fdf
