### ISSUE TITLE
TCC Keep crashing on login after todays updates

### ISSUE THREAD

**Issue by Arrchii** [Foglio1024/Tera-custom-cooldowns#61]

**Comment by Foglio1024** [comment]
Does it crash on v0.6.6? Send me error.txt so I can check it.

**Comment by Arrchii** [comment]
i belive, its this one 
[error.txt](https://github.com/Foglio1024/Tera-custom-cooldowns/files/1173045/error.txt)

**Comment by Foglio1024** [comment]
Ok I think I found the issue. It should only happen when logging in an archer. I'll release a fix later today.

**Comment by Arrchii** [comment]
Thank, you very much ;)
