### ISSUE TITLE
0.6.8 missing cooldown icon

### ISSUE THREAD

**Issue by crvN** [Foglio1024/Tera-custom-cooldowns#62]
archer's thunderbolt cd icon is missing

**Comment by Foglio1024** [comment]
in which window?

**Comment by crvN** [comment]
in cooldown bar

**Comment by Foglio1024** [comment]
Do you have class window disabled?

**Comment by crvN** [comment]
yes

**Comment by crvN** [comment]
i was wrong, class window was enabled, only visability was disabled. all is fine now.
