### ISSUE TITLE
0.7.2 crashes

### ISSUE THREAD

**Issue by crvN** [Foglio1024/Tera-custom-cooldowns#65]
[error.txt](https://github.com/Foglio1024/Tera-custom-cooldowns/files/1193592/error.txt)

**Comment by Foglio1024** [comment]
Yeah, needs update after RU patch. You can copy them from Shinra before i release the update.

**Comment by crvN** [comment]
i've already noticed that, thx. :)

**Comment by Foglio1024** [comment]
Fixed in v0.7.3
