### ISSUE TITLE
Using the latest ver and it keeps crashing when i do dungeon

### ISSUE THREAD

**Issue by kivelz** [Foglio1024/Tera-custom-cooldowns#69]
[error-1.txt](https://github.com/Foglio1024/Tera-custom-cooldowns/files/1225430/error-1.txt)

**Comment by kivelz** [comment]
playing on NA server

**Comment by Foglio1024** [comment]
Found the issue. It happens when teleporting if you have boss window disabled. You can keep it enabled until i release a fix.
