### ISSUE TITLE
UI hide

### ISSUE THREAD

**Issue by SakuraP3** [Foglio1024/Tera-custom-cooldowns#70]
I have a question regarding to this UI, does it replaces the original Tera UI or just kinda like adds a "new layer" ? because when I installed it added the new UI but I was still able to see the default UI from Tera, so is there a way to hide the old Tera UI without control+z ?

**Comment by Foglio1024** [comment]
It's a separate application which runs on top of the game. If you want to hide game's default UI items you can head over Tera DPS discord and look for the modded gpk files discord.gg/anUXQTp
