### ISSUE TITLE
0.8.13 error

### ISSUE THREAD

**Issue by evinidre** [Foglio1024/Tera-custom-cooldowns#75]
[error.txt](https://github.com/Foglio1024/Tera-custom-cooldowns/files/1273132/error.txt)

after copying 319982.txt and smt_319982 from shinra meter as it was missing from the TCC opcode folder

**Comment by Foglio1024** [comment]
Seems like S_FRIEND_LIST opcode is wrong in that file

**Comment by evinidre** [comment]
found the right opcode for S_FRIEND_LIST. TCC is now working. 
thanks.
