### ISSUE TITLE
TERA data protocole 319982 unfound

### ISSUE THREAD

**Issue by Xrhoys** [Foglio1024/Tera-custom-cooldowns#76]

**Comment by Foglio1024** [comment]
NA protocol has not been fully mapped for TCC yet, so it's not been included in the latest update.

**Comment by SaltyMonkey** [comment]
You can try to add NA protocol manually from https://github.com/meishuu/tera-data.
Files: protocol.319982.map and sysmsg.319982.map
Rename file protocol.319982.map to 319982.txt, open 319982.txt and delete all text what starts from # (# should be deleted too)
Rename file sysmsg.319982.map to smt_319982.txt
Copypaste yout txt files to {TCCFolder}\resources\data\opcodes

**Comment by Foglio1024** [comment]
That file is missing all of these though:
```
S_USER_EFFECT
S_BAN_PARTY_MEMBER
S_BAN_PARTY
S_PARTY_MEMBER_CHANGE_MP
S_CHECK_TO_READY_PARTY_FIN
S_RESULT_ITEM_BIDDING
S_RESULT_BIDDING_DICE_THROW
S_PARTY_MEMBER_BUFF_UPDATE
S_PARTY_MEMBER_ABNORMAL_ADD
S_PARTY_MEMBER_ABNORMAL_REFRESH
S_PARTY_MEMBER_ABNORMAL_DEL
S_PARTY_MEMBER_ABNORMAL_CLEAR
S_LEAVE_PRIVATE_CHANNEL
S_SYSTEM_MESSAGE_LOOT_ITEM
S_USER_BLOCK_LIST
S_ACCOMPLISH_ACHIEVEMENT
S_UPDATE_FRIEND_INFO
S_NOTIFY_TO_FRIENDS_WALK_INTO_SAME_AREA
S_ACCOUNT_PACKAGE_LIST
S_GUILD_TOWER_INFO
C_INVITE_USER_TO_GUILD
C_DELETE_FRIEND
C_PARTY_APPLICATION_DENIED
C_CHANGE_PARTY_MEMBER_AUTHORITY
C_CHANGE_PARTY_MANAGER
```

**Comment by SaltyMonkey** [comment]
Then you can't :)

**Comment by tilteddev** [comment]
Anyone from NA working on those missing opcodes?

**Comment by Xrhoys** [comment]
I tried what salty said before posting this, but didn't work.
[error.txt](https://github.com/Foglio1024/Tera-custom-cooldowns/files/1275070/error.txt)
I guess that's what Foglio mentionned ... ty for replying anyway, waiting for futur update ;D

**Comment by Foglio1024** [comment]
We're working on a tool to detect opcodes. Updates for meter and TCC will be faster once it's finished.

**Comment by kivelz** [comment]
copy the alt codes from shinra it works for me but it crashes if I use valk. no issue with other classes
