### ISSUE TITLE
Boss gague bar is biggerr than ususal

### ISSUE THREAD

**Issue by kivelz** [Foglio1024/Tera-custom-cooldowns#77]
Hi foglio,
The boss gauge is bigger than usual there is this black border surrounding the boss gauge bar covering up lot of things.

![image](https://user-images.githubusercontent.com/28724299/30256163-2e585a1e-96db-11e7-86e4-16812788aa0e.png)

**Comment by Gl0** [comment]
enable transparency in settings and restart TCC
