### ISSUE TITLE
Nothing works?

### ISSUE THREAD

**Issue by formatme** [Foglio1024/Tera-custom-cooldowns#78]
What am i suppose to see in game, i only see the thing on the left and no ui in game and chatbox messed up, Tera is in window mode.

**Comment by Foglio1024** [comment]
Most of the items are hidden by default. Using skills triggers visibility on. At first start all of them should be in the top left corner of the screen. Also if TCC icon in system tray doesen't turn green after login, it means that TCC is not reading game data.

**Comment by formatme** [comment]
It's green. i dont seen anything changed with my hud.. nothing at the top left and i dont see thecharacter panel. checked and it says enabled unless red is disabled and black is enabled.

like this does not show up anywhere ? how do i get it too 
https://imgur.com/5JDYFEw not my picture

**Comment by formatme** [comment]
Might because im using windows 10 insider preview?

**Comment by Foglio1024** [comment]
Could be a cause but I can't say for sure.

**Comment by neowutran** [comment]
you can try alt-tabbing few times ( & wait few second between alt tab ). And double check you are really in windowed mode
Recent version of windows have issues with windows focus management
