### ISSUE TITLE
8.29 and 30 error

### ISSUE THREAD

**Issue by tembelvesisko** [Foglio1024/Tera-custom-cooldowns#79]
[error.txt](https://github.com/Foglio1024/Tera-custom-cooldowns/files/1421843/error.txt)

**Comment by Foglio1024** [comment]
https://github.com/Foglio1024/Tera-custom-cooldowns/releases/tag/v0.8.28

- Reworked event parsing: **event times must now be specified in the hh:mm (24h) format, old files will crash TCC: delete events file if you never used it or update it to the new format**
