### ISSUE TITLE
TCC keep crashing

### ISSUE THREAD

**Issue by Arrchii** [Foglio1024/Tera-custom-cooldowns#80]
As in title,its 100% crash if  i invite more than one person to party. I have everything updatet do newest verson, pls help .
[error.txt](https://github.com/Foglio1024/Tera-custom-cooldowns/files/1431107/error.txt)

**Comment by Foglio1024** [comment]
You probably have no GroupAbnormals in tcc-config.xml (or you don't have the `class="Common"` one). Close TCC and delete everything from `<GroupAbnormals>` to `</GroupAbnormals>` in tcc-config.xml. Then restart TCC and it should create default values.

**Comment by Arrchii** [comment]
ughh my tcc config looks wierd, i dont even have <GroupAbnormals>, i can see only <GroupAbnormals />

<?xml version="1.0" encoding="utf-8"?>
<Settings>
  <WindowSettings>
    <WindowSetting Name="BossWindow" X="1146" Y="797" W="0" H="0" Visible="true" ClickThruMode="WhenUndim" Scale="1" AutoDim="false" DimOpacity="0.2" ShowAlways="false" AllowTransparency="false" Enabled="true" />
    <WindowSetting Name="BuffWindow" X="460" Y="88" W="0" H="0" Visible="true" ClickThruMode="WhenUndim" Scale="1" AutoDim="false" DimOpacity="0.2" ShowAlways="false" AllowTransparency="true" Enabled="true" />
    <WindowSetting Name="CharacterWindow" X="550" Y="872" W="0" H="0" Visible="true" ClickThruMode="WhenUndim" Scale="1" AutoDim="false" DimOpacity="0.2" ShowAlways="false" AllowTransparency="false" Enabled="true" />
    <WindowSetting Name="CooldownWindow" X="548" Y="781" W="0" H="0" Visible="true" ClickThruMode="WhenUndim" Scale="1" AutoDim="false" DimOpacity="0.2" ShowAlways="false" AllowTransparency="false" Enabled="true" />
    <WindowSetting Name="GroupWindow" X="0" Y="67" W="0" H="0" Visible="true" ClickThruMode="WhenUndim" Scale="1" AutoDim="false" DimOpacity="0.2" ShowAlways="false" AllowTransparency="true" Enabled="true" />
    <WindowSetting Name="ClassWindow" X="1160" Y="492" W="0" H="0" Visible="true" ClickThruMode="WhenUndim" Scale="1" AutoDim="false" DimOpacity="0.2" ShowAlways="false" AllowTransparency="true" Enabled="true" />
    <WindowSetting Name="ChatWindow" X="0" Y="0" W="600" H="200" Visible="false" ClickThruMode="Never" Scale="1" AutoDim="false" DimOpacity="1" ShowAlways="false" AllowTransparency="true" Enabled="false" />
  </WindowSettings>
  <OtherSettings IgnoreMeInGroupWindow="false" IgnoreGroupBuffs="false" IgnoreGroupDebuffs="false" IgnoreRaidAbnormalitiesInGroupWindow="false" BuffsDirection="LeftToRight" CooldownBarMode="Fixed" ClickThruWhenDim="true" ClickThruInCombat="false" MaxMessages="500" SpamThreshold="2" FontSize="15" ShowChannel="true" ShowTimestamp="true" ShowOnlyBosses="false" DisablePartyMP="false" DisablePartyHP="false" DisablePartyAbnormals="false" ShowOnlyAggroStacks="true" LfgOn="true" ChatWindowOpacity="0.4" LastRun="2017-10-31T15:49:34.7401496+01:00" LastRegion="EU-EN" Webhook="" WebhookMessage="@here Guild BAM will spawn soon!" TwitchName="" TwitchToken="" TwitchChannelName="" GroupSizeThreshold="7" EnrageLabelMode="Remaining" />
  <EnabledChatChannels>
    <Channel name="Say" enabled="True" />
    <Channel name="Party" enabled="True" />
    <Channel name="Guild" enabled="True" />
    <Channel name="Area" enabled="True" />
    <Channel name="Trade" enabled="True" />
    <Channel name="Greet" enabled="True" />
    <Channel name="Private1" enabled="True" />
    <Channel name="Private2" enabled="True" />
    <Channel name="Private3" enabled="True" />
    <Channel name="Private4" enabled="True" />
    <Channel name="Private5" enabled="True" />
    <Channel name="Private6" enabled="True" />
    <Channel name="Private7" enabled="True" />
    <Channel name="Private8" enabled="True" />
    <Channel name="PartyNotice" enabled="True" />
    <Channel name="RaidNotice" enabled="True" />
    <Channel name="Emote" enabled="True" />
    <Channel name="Global" enabled="True" />
    <Channel name="Raid" enabled="True" />
    <Channel name="Notify" enabled="True" />
    <Channel name="Event" enabled="True" />
    <Channel name="Error" enabled="True" />
    <Channel name="Group" enabled="True" />
    <Channel name="GuildNotice" enabled="True" />
    <Channel name="Deathmatch" enabled="True" />
    <Channel name="ContractAlert" enabled="True" />
    <Channel name="GroupAlerts" enabled="True" />
    <Channel name="Loot" enabled="True" />
    <Channel name="Exp" enabled="True" />
    <Channel name="Money" enabled="True" />
    <Channel name="Megaphone" enabled="True" />
    <Channel name="GuildAdvertising" enabled="True" />
    <Channel name="SentWhisper" enabled="True" />
    <Channel name="ReceivedWhisper" enabled="True" />
    <Channel name="System" enabled="True" />
    <Channel name="TradeRedirect" enabled="True" />
    <Channel name="Enchant12" enabled="True" />
    <Channel name="Enchant15" enabled="True" />
    <Channel name="RaidLeader" enabled="True" />
    <Channel name="Bargain" enabled="True" />
    <Channel name="Apply" enabled="True" />
    <Channel name="Death" enabled="True" />
    <Channel name="Ress" enabled="True" />
    <Channel name="Quest" enabled="True" />
    <Channel name="Friend" enabled="True" />
    <Channel name="Enchant7" enabled="True" />
    <Channel name="Enchant8" enabled="True" />
    <Channel name="Enchant9" enabled="True" />
    <Channel name="Laurel" enabled="True" />
    <Channel name="TCC" enabled="True" />
    <Channel name="Twitch" enabled="True" />
  </EnabledChatChannels>
  <ChatTabsSettings>
    <Tab name="ALL">
      <ExcludedAuthor value="System" />
    </Tab>
    <Tab name="GUILD">
      <Channel value="Guild" />
      <Channel value="GuildNotice" />
    </Tab>
    <Tab name="GROUP">
      <Channel value="Party" />
      <Channel value="PartyNotice" />
      <Channel value="RaidLeader" />
      <Channel value="RaidNotice" />
      <Channel value="Raid" />
      <Channel value="Ress" />
      <Channel value="Death" />
      <Channel value="Group" />
      <Channel value="GroupAlerts" />
    </Tab>
    <Tab name="WHISPERS">
      <Channel value="ReceivedWhisper" />
      <Channel value="SentWhisper" />
    </Tab>
    <Tab name="SYSTEM">
      <Author value="System" />
    </Tab>
  </ChatTabsSettings>
  <GroupAbnormals />
</Settings>

**Comment by Arrchii** [comment]
<?xml version="1.0" encoding="utf-8"?>
<Settings>
  <WindowSettings>
    <WindowSetting Name="BossWindow" X="1146" Y="797" W="0" H="0" Visible="true" ClickThruMode="WhenUndim" Scale="1" AutoDim="false" DimOpacity="0.2" ShowAlways="false" AllowTransparency="false" Enabled="true" />
    <WindowSetting Name="BuffWindow" X="460" Y="88" W="0" H="0" Visible="true" ClickThruMode="WhenUndim" Scale="1" AutoDim="false" DimOpacity="0.2" ShowAlways="false" AllowTransparency="true" Enabled="true" />
    <WindowSetting Name="CharacterWindow" X="550" Y="872" W="0" H="0" Visible="true" ClickThruMode="WhenUndim" Scale="1" AutoDim="false" DimOpacity="0.2" ShowAlways="false" AllowTransparency="false" Enabled="true" />
    <WindowSetting Name="CooldownWindow" X="548" Y="781" W="0" H="0" Visible="true" ClickThruMode="WhenUndim" Scale="1" AutoDim="false" DimOpacity="0.2" ShowAlways="false" AllowTransparency="false" Enabled="true" />
    <WindowSetting Name="GroupWindow" X="0" Y="67" W="0" H="0" Visible="true" ClickThruMode="WhenUndim" Scale="1" AutoDim="false" DimOpacity="0.2" ShowAlways="false" AllowTransparency="true" Enabled="true" />
    <WindowSetting Name="ClassWindow" X="1160" Y="492" W="0" H="0" Visible="true" ClickThruMode="WhenUndim" Scale="1" AutoDim="false" DimOpacity="0.2" ShowAlways="false" AllowTransparency="true" Enabled="true" />
    <WindowSetting Name="ChatWindow" X="0" Y="0" W="600" H="200" Visible="false" ClickThruMode="Never" Scale="1" AutoDim="false" DimOpacity="1" ShowAlways="false" AllowTransparency="true" Enabled="false" />
  </WindowSettings>
  <OtherSettings IgnoreMeInGroupWindow="false" IgnoreGroupBuffs="false" IgnoreGroupDebuffs="false" IgnoreRaidAbnormalitiesInGroupWindow="false" BuffsDirection="LeftToRight" CooldownBarMode="Fixed" ClickThruWhenDim="true" ClickThruInCombat="false" MaxMessages="500" SpamThreshold="2" FontSize="15" ShowChannel="true" ShowTimestamp="true" ShowOnlyBosses="false" DisablePartyMP="false" DisablePartyHP="false" DisablePartyAbnormals="false" ShowOnlyAggroStacks="true" LfgOn="true" ChatWindowOpacity="0.4" LastRun="2017-10-31T15:49:34.7401496+01:00" LastRegion="EU-EN" Webhook="" WebhookMessage="@here Guild BAM will spawn soon!" TwitchName="" TwitchToken="" TwitchChannelName="" GroupSizeThreshold="7" EnrageLabelMode="Remaining" />
  <EnabledChatChannels>
    <Channel name="Say" enabled="True" />
    <Channel name="Party" enabled="True" />
    <Channel name="Guild" enabled="True" />
    <Channel name="Area" enabled="True" />
    <Channel name="Trade" enabled="True" />
    <Channel name="Greet" enabled="True" />
    <Channel name="Private1" enabled="True" />
    <Channel name="Private2" enabled="True" />
    <Channel name="Private3" enabled="True" />
    <Channel name="Private4" enabled="True" />
    <Channel name="Private5" enabled="True" />
    <Channel name="Private6" enabled="True" />
    <Channel name="Private7" enabled="True" />
    <Channel name="Private8" enabled="True" />
    <Channel name="PartyNotice" enabled="True" />
    <Channel name="RaidNotice" enabled="True" />
    <Channel name="Emote" enabled="True" />
    <Channel name="Global" enabled="True" />
    <Channel name="Raid" enabled="True" />
    <Channel name="Notify" enabled="True" />
    <Channel name="Event" enabled="True" />
    <Channel name="Error" enabled="True" />
    <Channel name="Group" enabled="True" />
    <Channel name="GuildNotice" enabled="True" />
    <Channel name="Deathmatch" enabled="True" />
    <Channel name="ContractAlert" enabled="True" />
    <Channel name="GroupAlerts" enabled="True" />
    <Channel name="Loot" enabled="True" />
    <Channel name="Exp" enabled="True" />
    <Channel name="Money" enabled="True" />
    <Channel name="Megaphone" enabled="True" />
    <Channel name="GuildAdvertising" enabled="True" />
    <Channel name="SentWhisper" enabled="True" />
    <Channel name="ReceivedWhisper" enabled="True" />
    <Channel name="System" enabled="True" />
    <Channel name="TradeRedirect" enabled="True" />
    <Channel name="Enchant12" enabled="True" />
    <Channel name="Enchant15" enabled="True" />
    <Channel name="RaidLeader" enabled="True" />
    <Channel name="Bargain" enabled="True" />
    <Channel name="Apply" enabled="True" />
    <Channel name="Death" enabled="True" />
    <Channel name="Ress" enabled="True" />
    <Channel name="Quest" enabled="True" />
    <Channel name="Friend" enabled="True" />
    <Channel name="Enchant7" enabled="True" />
    <Channel name="Enchant8" enabled="True" />
    <Channel name="Enchant9" enabled="True" />
    <Channel name="Laurel" enabled="True" />
    <Channel name="TCC" enabled="True" />
    <Channel name="Twitch" enabled="True" />
  </EnabledChatChannels>
  <ChatTabsSettings>
    <Tab name="ALL">
      <ExcludedAuthor value="System" />
    </Tab>
    <Tab name="GUILD">
      <Channel value="Guild" />
      <Channel value="GuildNotice" />
    </Tab>
    <Tab name="GROUP">
      <Channel value="Party" />
      <Channel value="PartyNotice" />
      <Channel value="RaidLeader" />
      <Channel value="RaidNotice" />
      <Channel value="Raid" />
      <Channel value="Ress" />
      <Channel value="Death" />
      <Channel value="Group" />
      <Channel value="GroupAlerts" />
    </Tab>
    <Tab name="WHISPERS">
      <Channel value="ReceivedWhisper" />
      <Channel value="SentWhisper" />
    </Tab>
    <Tab name="SYSTEM">
      <Author value="System" />
    </Tab>
  </ChatTabsSettings>
  <GroupAbnormals />
</Settings>

**Comment by Arrchii** [comment]
i can't attach my config, because format is not suported

**Comment by Foglio1024** [comment]
Delete `<GroupAbnormals/>` and restart TCC then

**Comment by Arrchii** [comment]
usually i deleting my whole config,with launching TCC  because of black square's on desktop, they are always ther when i close and open tcc with no delete config file.
![black square](https://user-images.githubusercontent.com/30435436/32232129-a7d8e69e-be57-11e7-9567-4c04cbcab888.jpg)

**Comment by Foglio1024** [comment]
Black squares means that you disabled transparency on some windows. You have to enable it and restart TCC.

**Comment by Arrchii** [comment]
it help witch party crashing, thank you. So its mean im forced to use transparency, right ?

**Comment by Foglio1024** [comment]
Transparency setting was added for some people who wanted to stream with some software which didn't see transparent windows. It should be kept always on.

**Comment by Arrchii** [comment]
Oh, thank you very much for fast response and help, its working good now,
