### ISSUE TITLE
Boss HP bar

### ISSUE THREAD

**Issue by m4ch1** [Foglio1024/Tera-custom-cooldowns#83]
Hello id like to ask if its possible to combine lets say TCC 0.9.2 with the boss hp bar from TCC 0.8.27. Personaly I prefered the old layout, it feel like its too much hassle now with the sepparated bar for enrage timer and percentage number on side, before I looked in one spot and I knew all the info I needed. I feel like with the new layout I have to check multiple spots on the boss hp bar to get the info I want. Could please tell me if I can just swap some files arround and merge somehow the "older TCC boss hp bar" with the new version.

**Comment by Foglio1024** [comment]
I would add a switch to make users able to choose the layout they want, but I don't have time to do it.

**Comment by m4ch1** [comment]
Thanks thats awesome and yeah dont worry, no rush its not big deal. Thank your for the fast reply, you're doing really good job with TCC keep it up ;)
