### ISSUE TITLE
TCC V.0.9.3 Fixed Cooldown Lag

### ISSUE THREAD

**Issue by KhazerD98** [Foglio1024/Tera-custom-cooldowns#84]
I have noticed with the recent TCC update, the fixed cooldowns have been lagging.  The cooldown animation on the skills get really choppy especially in the dungeons. While in the open world it seems to be okay. But, in dungeons, the cooldowns seem like they are lagging behind and eventually lag so hard behind the cooldowns are no longer usable.

**Comment by Foglio1024** [comment]
I don't have time to work on it. The only advice I can give you is to lower Tera's GPU usage (e.g. enabling fps smoothing and setting max framerate to lower value in `S1Engine.ini`. There's already an `S1Engine.ini` in #faq channel in Tera DPS Discord for this purpose).

**Comment by Foglio1024** [comment]
Should be fixed in v0.9.5
