### ISSUE TITLE
doesn't work after NA update

### ISSUE THREAD

**Issue by AETM132** [Foglio1024/Tera-custom-cooldowns#85]
Hello! the TCC seems activate it but now after the new patch, doesn't appear anything in game, i check if im in windows mode and nothing works. the menu on left side appears but nothing more.

**Comment by Stu92** [comment]
have the same problem

**Comment by AETM132** [comment]
i fix the problem, just copy the last shinra meter opcodes and paste it to the opcodes' folder of TCC and that's it

**Comment by samtera** [comment]
I've copied over the opcodes from Shinra and it still doesn't seem to be working for me. Could you send me a link to the Github where you're getting the opcodes from? Also do you just drop the opcode files into the TTC opcode folder, copying any new files in and replacing any of the same?

**Comment by Foglio1024** [comment]
Should be fixed with 0.9.4
