### ISSUE TITLE
TCC-0.9.5\resources\data\opcodes\324671.txt" konnte nicht gefunden werden

### ISSUE THREAD

**Issue by Tehinc** [Foglio1024/Tera-custom-cooldowns#87]
Why?

##### CRASH #####
Die Datei "D:\Download\Tera\TCC-0.9.5\resources\data\opcodes\324671.txt" konnte nicht gefunden werden.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   bei System.IO.StreamReader..ctor(String path, Encoding encoding)
   bei System.IO.File.ReadLines(String path)
   bei Tera.Game.OpCodeNamer.ReadOpCodeFile(String filename) in I:\Progetti VS\TCC\TCC.Core\TeraCommon\Game\Services\OpCodeNamer.cs:Zeile 37.
   bei TCC.Parsing.PacketProcessor.MessageReceived(Message obj) in I:\Progetti VS\TCC\TCC.Core\Parsing\PacketRouter.cs:Zeile 76.
   bei Tera.Sniffing.MessageSplitter.ClientBlockFinished(Byte[] block) in I:\Progetti VS\TCC\TCC.Core\TeraCommon\Sniffing\MessageSplitter.cs:Zeile 42.
   bei Tera.PacketLog.BlockSplitter.PopAllBlocks() in I:\Progetti VS\TCC\TCC.Core\TeraCommon\PacketLog\Parsing\BlockSplitter.cs:Zeile 66.
   bei DamageMeter.Sniffing.TeraSniffer.HandleClientToServerDecrypted(Byte[] data) in I:\Progetti VS\TCC\TCC.Core\Sniffing\TeraSniffer.cs:Zeile 217.
   bei DamageMeter.Sniffing.TeraSniffer.HandleTcpDataReceived(TcpConnection connection, Byte[] data, Int32 needToSkip) in I:\Progetti VS\TCC\TCC.Core\Sniffing\TeraSniffer.cs:Zeile 191.
   bei NetworkSniffer.TcpConnection.HandleTcpReceived(UInt32 sequenceNumber, Byte[] data) in I:\Progetti VS\TCC\TCC.Core\Sniffing\TcpConnection.cs:Zeile 68.
   bei NetworkSniffer.TcpSniffer.Receive(IPv4Packet ipData) in I:\Progetti VS\TCC\TCC.Core\Sniffing\TcpSniffer.cs:Zeile 103.
   bei NetworkSniffer.IpSnifferWinPcap.device_OnPacketArrival(Object sender, CaptureEventArgs e) in I:\Progetti VS\TCC\TCC.Core\Sniffing\IpSnifferWinPcap.cs:Zeile 148.
   bei SharpPcap.LibPcap.PcapDevice.SendPacketArrivalEvent(RawCapture p)
   bei SharpPcap.LibPcap.LibPcapSafeNativeMethods.pcap_dispatch(IntPtr adaptHandle, Int32 count, pcap_handler callback, IntPtr ptr)
   bei SharpPcap.LibPcap.PcapDevice.CaptureThread()
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Threading.ThreadHelper.ThreadStart()
mscorlib

**Comment by Foglio1024** [comment]
EU had patch today. TCC won't work until next update. You can copy `324671.txt` and `smt_324671.txt` from ShinraMeter folder if you want to temporarily make it work, but it will still miss some database data until next release.
