### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Yafity** [Foglio1024/Tera-custom-cooldowns#88]
[error.txt](https://github.com/Foglio1024/Tera-custom-cooldowns/files/1566172/error.txt)
RU Tera crashes when I log on my priest(but works on other one)

**Comment by Foglio1024** [comment]
You have some very long item cooldown on that causes it to crash. I won't have time to fix it until next week.

**Comment by Yafity** [comment]
@Foglio1024 still not working (even after maintenance)

**Comment by Foglio1024** [comment]
Fixed in 0.9.8
