### ISSUE TITLE
not really an issue more of a question

### ISSUE THREAD

**Issue by NovaSilent** [Foglio1024/Tera-custom-cooldowns#90]
i dont understand how to start the application i went and found the icon in the files hoping to find the application but i can't find anything i was wondering do i need to put this folder into proxy or should there be a seperate way to start the application

**Comment by Foglio1024** [comment]
https://github.com/Foglio1024/Tera-custom-cooldowns/releases/download/v0.9.7/TCC-0.9.7.zip
