### ISSUE TITLE
Doesn't show anything ingame

### ISSUE THREAD

**Issue by Miyume** [Foglio1024/Tera-custom-cooldowns#91]
Russian localisation. 
So I decided to get myself a tcc and for some reason it doesn't show anything in game. I have created a rule for it and tried setting winpcap to false in a "windows.xml" file, tried doing otherwise, still nothing. For ex. when I JUST turn on tcc I can see transparent hp bar and some stuff appearing in left upper corner and then quickly disappearing, I thought that's ok since the program was turned on without the game. Ahem, so.. Ui stuff appears without the game for a millisecond but doesn't show anything ingame, pretty much sure I runner the game in a needed windowed ugh...format, I guess. Can I run tcc somehow? 
Btw red other "issues" and found someone saying things like "tcc icon turning green" in tray, I also don't remember mine turning into anything but red, is it the problem too?

**Comment by Foglio1024** [comment]
Yes, if icon stays red it means that TCC didn't detect your connection to game server. That's probably caused by incorrect configuration.

**Comment by Miyume** [comment]
Can I do anything to fix it? I really want to use TCC :/ Pretty much that's why I was so sad it didn't run properly, I'm just not really good at handling programs by myself, so if something doesn't work I don't know what to do or what did I do wrong.

**Comment by Foglio1024** [comment]
Try following setup guide here: https://github.com/neowutran/ShinraMeter/wiki#prerequisite

**Comment by Miyume** [comment]
Thank you very much, I'll try some things from here, I hope I want too much of a nuisance.
