### ISSUE TITLE
Crashing randomly, once during dungeon, once in town.

### ISSUE THREAD

**Issue by jxlah** [Foglio1024/Tera-custom-cooldowns#94]
[error.txt](https://github.com/Foglio1024/Tera-custom-cooldowns/files/1626720/error.txt)
getting the above error with the error message that says something like "an error has occured, TCC will now close. Check the error.txt for more info."

**Comment by Foglio1024** [comment]
Should be fixed in 5ea72526176ad5ec78a2b71251c2a00b92f0be80.
