### ISSUE TITLE
The buff bar

### ISSUE THREAD

**Issue by Coniflex** [Foglio1024/Tera-custom-cooldowns#95]
Hello,

I was wondering if i could remove common buffs? I'd if possible only want to see dragon/phoenix and brooch buffs on buff bar.
I hate searching in the middle of 30 other buffs how long my dragon/phoenix or brooch is up so i hoped i could find it in here but without succes so far.

Kind regards,
Coniflex

**Comment by Foglio1024** [comment]
Buffs in buff bar can't be configured, but Dragon/Phoenix/Brooch cooldowns can be displayed in cooldown window.
