### ISSUE TITLE
Unknown client version: 326440 

### ISSUE THREAD

**Issue by abrakadabra01** [Foglio1024/Tera-custom-cooldowns#97]
This message popup when i start my tera. I can go to my settings but mu UI is nowhere to be found, even when i try to trigger something by using skills.

Is there a fix for this?

kinds regard,
abrakadabra01

**Comment by primuskilli** [comment]
I have the same problem. Please help

**Comment by SaltyMonkey** [comment]
open in TCC `\resources\data\opcodes`
delete all
copypaste `resources\data\opcodes` from ShinraMeter
